### ISSUE TITLE
Issues comments after review

### ISSUE THREAD

**Issue by 4lexbit** [biometrickz/fastapi_f2f#1]

**Comment by 4lexbit** [comment]
separate the folder with the code and its dependencies on the environment files and configs

ur option:
|
|- app
|  |- ...
|  ...
|- config
|  |-.env
|  ...
|- Dockerfile
|- mypy.ini
|-...
...

more correct:
|
|- src
|   |- app
|   |- config
|
|- Dockerfile
|- .env
|- ...
...

**Comment by 4lexbit** [comment]
Remove s3 client and downloading functional

**Comment by 4lexbit** [comment]
remove prints

**Comment by 4lexbit** [comment]
use pre-declared exception classes for handling errors

**Comment by 4lexbit** [comment]
why u use requirement.txt if u have poetry

**Comment by 4lexbit** [comment]
instead mypy.ini and other, use global config file for whole projetc

**Comment by 4lexbit** [comment]
when building docker use poetry

https://github.com/biometrickz/fastapi_f2f/blob/8d20119b29fdac501cc25fe73d008147086449b6/Dockerfile#L19

**Comment by 4lexbit** [comment]
move to app config

https://github.com/biometrickz/fastapi_f2f/blob/8d20119b29fdac501cc25fe73d008147086449b6/config/config.py#L5

**Comment by 4lexbit** [comment]
don't use closing /

https://github.com/biometrickz/fastapi_f2f/blob/8d20119b29fdac501cc25fe73d008147086449b6/app/routers/f2f.py#L9C22-L9C23

**Comment by 4lexbit** [comment]
empty dir

https://github.com/biometrickz/fastapi_f2f/tree/8d20119b29fdac501cc25fe73d008147086449b6/app/models

**Comment by 4lexbit** [comment]
write more configuration attributes, add new class to Appconfig

https://github.com/biometrickz/fastapi_f2f/blob/8d20119b29fdac501cc25fe73d008147086449b6/app/main.py#L5

**Comment by 4lexbit** [comment]
build docker container and run a job in it

https://github.com/biometrickz/fastapi_f2f/blob/8d20119b29fdac501cc25fe73d008147086449b6/.github/workflows/ci.yml#L25

**Comment by 4lexbit** [comment]
extra dependencies in LINT case. Add or remove it


https://github.com/biometrickz/fastapi_f2f/blob/8d20119b29fdac501cc25fe73d008147086449b6/entrypoint.sh#L16

**Comment by rashtv** [comment]
All other issues: https://github.com/biometrickz/fastapi_f2f/commit/4d12f7789cea346c09b299c5b6fa2e9e214a350d

Github CI: https://github.com/biometrickz/fastapi_f2f/commit/17d38482b95de971465b4d8622180989155c1442
